version: '3'
services:
  python:
    build: .
    volumes:
      - ./files:/files
      - ./credential.json:/credential.json
    environment:
      - TITLE="Drivedump"

      - MONGO_URI=<MONGO_URI>
      
      - MAIL_ADMIN=<MAIL_ADMIN>
      - MAIL_SERVER=<MAIL_SERVER>
      - MAIL_USERNAME=<MAIL_USERNAME>
      - MAIL_PASSWORD=<MAIL_PASSWORD>
